---
version: 3

images:
 base_image:
   name: docker.io/redhat/ubi9:latest

dependencies:
 python_interpreter:
   package_system: python3
 ansible_core:
   package_pip: ansible-core
 ansible_runner:
   package_pip: ansible-runner
 system:
 - openssh-clients
 - sshpass
 galaxy:
   roles:
     - name: geerlingguy.apache 
     - name: geerlingguy.php 
   collections:
     - name: fedora.linux_system_roles

