---
on: 
  workflow_dispatch:
    inputs:
       name:
         description: 'CD Manual Testing'
         default: 'Continous Delivery'
         required: true
         type: string
jobs:
  deploy:
    name: Apply Configurations
    runs-on: ubuntu-latest
    environment: production
    steps:
     - name: Set up SSH
       run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
     - name: Install Ansible
       shell: bash
       run: |
           sudo apt update
           sudo apt install -y ansible 
     - name: Install Dependencies
       shell: bash
       run: |
           ansible-galaxy collection install --upgrade -r ../collections/requirements.yml
           ansible-galaxy role       install           -r ../roles/requirements.yml			  
     - name: Run Playbook
       shell: bash
       run: |
           ansible-playbook playbooks/main.yml --private-key private_key.pem
